### ISSUE TITLE
prototype

### ISSUE THREAD

**Issue by janroesler** [burning-duck/burning-duck#1]
Ok,

it looks like that the prototyping don't work like expected or i am doing something really wrong ^^
Used the Magnolia docs example and the configuration from the other project.
Or the backend site configuration is missing something. 

so, should we use simple setup, like the github project page or trying to get it right and running?

**Comment by pbit** [comment]
Should be ok to start without it.
We can still do gazillion things :metal: 

https://documentation.magnolia-cms.com/display/DOCS/Site+definition#Sitedefinition-DoIneedasitedefinition?

**Comment by janroesler** [comment]
OK,

i will test the prototype configuration on burning-duck.de if it fails , we use a other one. :)

**Comment by janroesler** [comment]
- [x] rename project
- [x] refactoring new name
- [x] checkout on the server
- [x] add site configuration to Magnolia
- [x] test configuration and light module

**Comment by janroesler** [comment]
So, i don't get this working.

prototype.yaml
```
dialog: mte:pages/pageProperties
class: info.magnolia.module.site.templates.PrototypeTemplateDefinition

templateScript: /burning-duck/templates/pages/main.ftl
renderType: site
type: feature

jsFiles:
  - link: https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.10/semantic.min.js
    addFingerPrint: true

areas:
  htmlHeader:
    createAreaNode: false
    renderType: freemarker
    templateScript: /burning-duck/templates/pages/areas/htmlHeader.ftl
    type: noComponent
  nav:
    createAreaNode: false
    renderType: freemarker
    templateScript: /burning-duck/templates/pages/areas/nav.ftl
    type: noComponent
  main:
    type: list
  footer:
    createAreaNode: false
    editable: false
    renderType: freemarker
    templateScript: /burning-duck/templates/pages/areas/footer.ftl
    type: noComponent
```

main.ftl
```
[#-------------- RENDERING --------------]
<!DOCTYPE html>
    <!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7" xml:lang="${cmsfn.language()}" lang="${cmsfn.language()}"><![endif]-->
    <!--[if IE 7]><html class="no-js lt-ie9 lt-ie8" xml:lang="${cmsfn.language()}" lang="${cmsfn.language()}"><![endif]-->
    <!--[if IE 8]><html class="no-js lt-ie9" xml:lang="${cmsfn.language()}" lang="${cmsfn.language()}"><![endif]-->
    <!--[if gt IE 8]><!--><html class="no-js" xml:lang="${cmsfn.language()}" lang="${cmsfn.language()}"><!--<![endif]-->
    <head>
        [@cms.page /]
        [@cms.area name="htmlHeader"/]
    </head>
    <body>
        [@cms.area name="nav"/]
        [@cms.area name="main"/]
        [@cms.area name="footer"/]

        [#-- We're using the prototype's jsFiles to be rendered at the bottom of the page --]
        [#if def.jsFiles??]
            [#list def.jsFiles as jsFile]
            <script src="${jsFile.link}"></script>
            [/#list]
        [/#if]
    </body>
</html>
```

burning-duck.yaml
```
renderType: site
title: burning-duck
areas:
  main:
    type: list
    availableComponents:
      textImage:
        id: mtk:components/textImage
  footer:
    editable: true
```

The site configuration
![2017-04-05 08_42_31-magnolia 5](https://cloud.githubusercontent.com/assets/2596518/24693038/ed893480-19db-11e7-9c6a-b2d6e198622f.png)

I can add the page but when i want it to edit i get the following
```
Template Error!

Error while rendering [/burning-duck] with template [burning-duck:pages/burning-duck] for URI [/burning-duck?mgnlPreview=false&mgnlChannel=desktop]:
RenderException: No template script defined for the template definition [info.magnolia.rendering.template.configured.ConfiguredTemplateDefinition@3f854191[id=burning-duck:pages/burning-duck,name=burning-duck,renderType=site,description=<null>,title=burning-duck,templateScript=<null>,autoGeneration=info.magnolia.rendering.template.configured.ConfiguredAutoGeneration@2d84ee53[content={},generatorClass=<null>]]]
```
